### ISSUE TITLE
feat request: Brat remix album style covers

### ISSUE THREAD

**Issue by datawater** [retronav/bratify#3]
Feature request to add the ability to generate remix album style covers.

The only difference between normal and remix album cover styles, is that the remix album is mirrored, so it should be pretty easy to implement.
![image](https://github.com/user-attachments/assets/ce4c881e-2481-4fbe-8dc0-d557bef3105c)

**Comment by retronav** [comment]
@datawater I believe this is already added in https://github.com/retronav/bratify/commit/199422109181c65a67a1715a3640e4486a284151. Closing this, feel free to re open this issue.
